### ISSUE TITLE
Arguments on scalar types?

### ISSUE THREAD

**Issue by lsanwick** [rmosolgo/graphql-ruby#1133]
Looking at the docs, it appears that if I define my own scalar types, there is no way to define arguments for them to take.  The GraphQL documentation gives examples of using arguments with scalar types (like here: http://graphql.org/learn/queries/#arguments), is there any way to do this in graphql-ruby?

**Comment by rmosolgo** [comment]
Yes, those are _field_ arguments, for example: 

```ruby
field :phoneNumber, types.String do 
  argument :includeCountryCode, types.Boolean, default_value: true 
  resolve ->(obj, args, ctx) { ... } 
end 
```

could be used as: 

```graphql 
phoneNumber(includeCountryCode: false) 
# => "555-1234"
```

For custom scalars, the only change is to switch `types.String` for your custom `Types::PhoneNumberType`: 

```ruby
field :phoneNumber, Types::PhoneNumberType do 
  argument :includeCountryCode, types.Boolean, default_value: true 
  resolve ->(obj, args, ctx) { ... } 
end 
```

Usage is the same as above:

```graphql 
phoneNumber(includeCountryCode: false) 
# => "555-1234"
```

But your custom `PhoneNumberType` will be used to format the value.

Hope that helps, feel free to follow up here if you have any more trouble!

**Comment by lsanwick** [comment]
Thanks for the reply @rmosolgo, that's helpful! In my case I'd like to have a TimeType that takes a `format` argument to determine how to render the time, but I would prefer to not have that format switching logic occurring in multiple places around my schema. Is there any recommendation on the proper way to encapsulate that logic?

**Comment by rmosolgo** [comment]
It sounds like there would be many different fields (`Event.startsAt`, `Room.reservedUntil`, `Notification.dismissedAt`) that would each take a `format:` argument, right? And they should all perform the same string formatting based on the `format:` value. 

It seems like a [resolve wrapper](http://graphql-ruby.org/fields/resolve_wrapper.html) might do the job. The inner `resolve` function could return the proper Ruby `DateTime`, then the wrapper could perform formatting into a String, based on the argument value.

**Comment by 00dav00** [comment]
Hi @rmosolgo, after updating to `1.10` a project I work with started raising the exception described in this issue: https://github.com/jetruby/apollo_upload_server-ruby/issues/24

```
Failures:

  1) ActivityLog userActivityLog returns activity for the current user
     Failure/Error: mutation(Types::MutationType)
     
     ArgumentError:
       Can't add legacy type: Upload (GraphQL::ScalarType)
     # /home/david/.rvm/gems/ruby-2.6.5/gems/graphql-1.10.0/lib/graphql/schema.rb:1770:in `add_type'
     # /home/david/.rvm/gems/ruby-2.6.5/gems/graphql-1.10.0/lib/graphql/schema.rb:1814:in `block in add_type'
     # /home/david/.rvm/gems/ruby-2.6.5/gems/graphql-1.10.0/lib/graphql/schema.rb:1811:in `each'
     # /home/david/.rvm/gems/ruby-2.6.5/gems/graphql-1.10.0/lib/graphql/schema.rb:1811:in `add_type'
     # /home/david/.rvm/gems/ruby-2.6.5/gems/graphql-1.10.0/lib/graphql/schema.rb:1806:in `block (2 levels) in add_type'
     # /home/david/.rvm/gems/ruby-2.6.5/gems/graphql-1.10.0/lib/graphql/schema.rb:1803:in `each'
     # /home/david/.rvm/gems/ruby-2.6.5/gems/graphql-1.10.0/lib/graphql/schema.rb:1803:in `block in add_type'
     # /home/david/.rvm/gems/ruby-2.6.5/gems/graphql-1.10.0/lib/graphql/schema.rb:1799:in `each'
     # /home/david/.rvm/gems/ruby-2.6.5/gems/graphql-1.10.0/lib/graphql/schema.rb:1799:in `add_type'
     # /home/david/.rvm/gems/ruby-2.6.5/gems/graphql-1.10.0/lib/graphql/schema.rb:1673:in `block in add_type_and_traverse'
     # /home/david/.rvm/gems/ruby-2.6.5/gems/graphql-1.10.0/lib/graphql/schema.rb:1673:in `each'
     # /home/david/.rvm/gems/ruby-2.6.5/gems/graphql-1.10.0/lib/graphql/schema.rb:1673:in `add_type_and_traverse'
     # /home/david/.rvm/gems/ruby-2.6.5/gems/graphql-1.10.0/lib/graphql/schema.rb:972:in `mutation'
     # ./app/graphql/app_schema.rb:3:in `<class:HolrSchema>'
     # ./app/graphql/app_schema.rb:1:in `<main>'
     # /home/david/.rvm/gems/ruby-2.6.5/gems/bootsnap-1.4.4/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:22:in `require'
     # /home/david/.rvm/gems/ruby-2.6.5/gems/bootsnap-1.4.4/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:22:in `block in require_with_bootsnap_lfi'
     # /home/david/.rvm/gems/ruby-2.6.5/gems/bootsnap-1.4.4/lib/bootsnap/load_path_cache/loaded_features_index.rb:92:in `register'
     # /home/david/.rvm/gems/ruby-2.6.5/gems/bootsnap-1.4.4/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:21:in `require_with_bootsnap_lfi'
     # /home/david/.rvm/gems/ruby-2.6.5/gems/bootsnap-1.4.4/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:30:in `require'
     # /home/david/.rvm/gems/ruby-2.6.5/gems/bootsnap-1.4.4/lib/bootsnap/load_path_cache/core_ext/active_support.rb:48:in `block in require_or_load'
     # /home/david/.rvm/gems/ruby-2.6.5/gems/bootsnap-1.4.4/lib/bootsnap/load_path_cache/core_ext/active_support.rb:16:in `allow_bootsnap_retry'
     # /home/david/.rvm/gems/ruby-2.6.5/gems/bootsnap-1.4.4/lib/bootsnap/load_path_cache/core_ext/active_support.rb:47:in `require_or_load'
     # /home/david/.rvm/gems/ruby-2.6.5/gems/bootsnap-1.4.4/lib/bootsnap/load_path_cache/core_ext/active_support.rb:60:in `block in load_missing_constant'
     # /home/david/.rvm/gems/ruby-2.6.5/gems/bootsnap-1.4.4/lib/bootsnap/load_path_cache/core_ext/active_support.rb:16:in `allow_bootsnap_retry'
     # /home/david/.rvm/gems/ruby-2.6.5/gems/bootsnap-1.4.4/lib/bootsnap/load_path_cache/core_ext/active_support.rb:59:in `load_missing_constant'
     # ./spec/support/contexts/graphql_test.rb:7:in `block (2 levels) in <main>'
     # ./spec/graphql_schema/activity_log_spec.rb:48:in `block (3 levels) in <top (required)>'

```

The `resolve wrapper` link is broken and I can't seem to find something with that name around the docs. Is there something, tried using the gem scalar as an argument in an [input type](https://graphql-ruby.org/type_definitions/input_objects) with the same result, the schema tried to evaluate the input type argument and the `Can't add legacy type` exception is raised.

Do you have any recommendations on how wrap this scalar so it can work as an argument?
