### ISSUE TITLE
Query execution fails because Array doesn't have the wrap method

### ISSUE THREAD

**Issue by opan** [rmosolgo/graphql-ruby#839]
Hi all! I have a little problem here. I am trying to use an `Argument` on my query. Here is my code:

```ruby

# frozen_string_literal: true

module ProcuraEngine
  module Presenter
    class MeasurementUnitGraphql < GraphqlBase
      MeasurementUnitType = GraphQL::ObjectType.define do
        name 'Measurement Unit'

        field :id, !types.ID
        field :ident_name, !types.String
        field :name, !types.String
        field :symbol, types.String
        field :desc, types.String
        field :created_at, DateTimeType
        field :updated_at, DateTimeType
        field :updated_by_id, !types.Int
        field :created_by_id, !types.Int
      end

      QueryType = GraphQL::ObjectType.define do
        name 'Query'

        field :items do
          type types[MeasurementUnitType]
          argument :id, types.ID, 'Measurement Unit ID'
          resolve -> (obj, args, context) do
            # binding.pry
            context[:measurement_unit_repo].query
          end
        end
        field :resource do
          type !types.String
          resolve -> (_obj, _args, _context) do
            'measurement_unit'
          end
          # resolve -> (_obj, _args, _context) { 'measurement_unit' }
        end
        field :total_server_items, !types.Int do
          resolve -> (_obj, _args, context) { context[:measurement_unit_repo].count }
        end
      end

      Schema = GraphQL::Schema.define do
        query QueryType
      end

      def execute(measurement_unit_repo, graphql_str = nil)
        graphql_str ||= %{
          query {
            resource
            total_server_items
            items {
              ident_name
              name
              symbol
              desc
              created_at
              created_by_id
            }
          }
        }
        binding.pry
        Schema.execute(graphql_str, context: { measurement_unit_repo: measurement_unit_repo })
      end
    end
  end
end


# Execution code

      query = %{
        query {
          resource
          total_server_items
          items(id: 1) {
            ident_name
            name
            symbol
            desc
            created_at
            created_by_id
          }
        }
      }

ProcuraEngine::Presenter::MeasurementUnitGraphql.new.execute(measurement_unit_repo, query)

```

I run these through rspec and the errors I get is:

```
 Failures:

  1) Main::Application /measurement_unit - GET filter should working properly
     Failure/Error: Schema.execute(graphql_str, context: { measurement_unit_repo: measurement_unit_repo })

     NoMethodError:
       undefined method `wrap' for Array:Class
     # ./lib/procura_engine/presenter/measurement_unit_graphql.rb:65:in `execute'
     # ./apps/main/web/controllers/measurement_unit_controller.rb:10:in `block (2 levels) in <class:Application>'
     # ./apps/main/web/controllers/measurement_unit_controller.rb:8:in `block in <class:Application>'
     # ./apps/main/web/controllers/application_controller.rb:9:in `block in <class:Application>'
     # ./spec/main/web/controllers/measurement_unit_controller_spec.rb:55:in `block (3 levels) in <top (required)>'
     # ./spec/spec_helper.rb:14:in `block (3 levels) in <top (required)>'
     # ./spec/spec_helper.rb:14:in `block (2 levels) in <top (required)>'

Finished in 3.93 seconds (files took 1.75 seconds to load)
15 examples, 1 failure
```

graphql version: 1.6.5 and I'm using this without Rails.

The backtrace is not clear enough, so I don't where to start debugging.
Is there anything I missed? Thank you for the response.
